### ISSUE TITLE
valid-animation-module 报错

### ISSUE THREAD

**Issue by chenzefeng09** [erha19/eslint-plugin-weex#1]
**Tell us about your environment**

* **ESLint Version:4.19.1**
* **eslint-plugin-weex Version:1.0.11**
* **Node Version:8.9.3**

**Please show your full configuration:**

```
module.exports = {
  extends: [
    'eslint-config-weex/vue',
  ],
  globals: {
   
  },
  rules: {
  }
};
```

**What did you do? Please include the actual source code causing the issue.**

```vue
moveLeft(){
                const body_1 = this.$refs.animate_body_1;
                const body_2 = this.$refs.animate_body_2;
                animation.transition(body_2, {
                    styles: {
                        transform: 'translateX(-200%)',
                    },
                    duration: 0, //ms
                }, function () {
            }
```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**
Cannot read property 'arguments' of undefined
TypeError: Cannot read property 'arguments' of undefined
    at prop.body.body.forEach.body (/Users/chenzefeng/Development/git_workspace/hybrid/node_modules/_eslint-plugin-weex@1.0.11@eslint-plugin-weex/lib/rules/vue/valid-animation-module.js:101:40)
    at Array.forEach (<anonymous>)
    at propsWithFunctionExpression.forEach.prop (/Users/chenzefeng/Development/git_workspace/hybrid/node_modules/_eslint-plugin-weex@1.0.11@eslint-plugin-weex/lib/rules/vue/valid-animation-module.js:100:24)
    at Array.forEach (<anonymous>)
    at utils.executeOnVue.obj (/Users/chenzefeng/Development/git_workspace/hybrid/node_modules/_eslint-plugin-weex@1.0.11@eslint-plugin-weex/lib/rules/vue/valid-animation-module.js:99:35)
    at ExportDefaultDeclaration:exit (/Users/chenzefeng/Development/git_workspace/hybrid/node_modules/_eslint-plugin-weex@1.0.11@eslint-plugin-weex/lib/utils/index.js:470:9)
    at listeners.(anonymous function).forEach.listener (/Users/chenzefeng/Development/git_workspace/hybrid/node_modules/_eslint@4.19.1@eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/chenzefeng/Development/git_workspace/hybrid/node_modules/_eslint@4.19.1@eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/chenzefeng/Development/git_workspace/hybrid/node_modules/_eslint@4.19.1@eslint/lib/util/node-event-generator.js:251:26)

下面这段代码中，animation.transition之前的两行会导致这个报错，删除这两行就不会
```vue
moveLeft(){
                const body_1 = this.$refs.animate_body_1;//这两行报错
                const body_2 = this.$refs.animate_body_2;//这两行导致报错
                animation.transition(body_2, {
                    styles: {
                        transform: 'translateX(-200%)',
                    },
                    duration: 0, //ms
                }, function () {
            }
```

**Comment by chenzefeng09** [comment]
@erha19   麻烦看下

**Comment by erha19** [comment]
@chenzefeng09 please provide your complete code, I can't find the problem with the code you have provided.

**Comment by erha19** [comment]
@chenzefeng09 I have published a new version for this issue, you can upgrade the version and check whether it can be work or not. Need your feedback.

**Comment by chenzefeng09** [comment]
work for me, thanks!  @erha19
