### ISSUE TITLE
weex/vue/no-document 和 weex/vue/no-global，在 method 里面使用 import 的方法有问题

### ISSUE THREAD

**Issue by biaomingzhong** [erha19/eslint-plugin-weex#2]
**Tell us about your environment**

* **ESLint Version:** "4.19.1"
* **eslint-plugin-weex Version:** "1.0.12"
* **Node Version:** "10.4.1"

**Please show your full configuration:**

```
// https://eslint.org/docs/user-guide/configuring

module.exports = {
  root: true,
  parserOptions: {
    parser: 'babel-eslint'
  },
  env: {
    browser: true
  },
  globals: {
    weex: true,
    WXEnvironment: true
  },
  extends: [
    // https://github.com/vuejs/eslint-plugin-vue#priority-a-essential-error-prevention
    // consider switching to `plugin:vue/strongly-recommended` or `plugin:vue/recommended` for stricter rules.
    'plugin:vue/recommended', 
    'eslint-config-weex',
    'eslint-config-weex/vue',
    // https://github.com/standard/standard/blob/master/docs/RULES-en.md
    'standard'
  ],
  // required to lint *.vue files
  plugins: [
    'vue'
  ],
  // add your custom rules here
  rules: {
    'vue/html-self-closing': ['error', {
      'html': {
        'void': 'never',
        'normal': 'any',
        'component': 'any'
      },
      'svg': 'always',
      'math': 'always'
    }],
    'vue/comment-directive': 'off',
    'vue/html-end-tags': 'off',
    'weex/vue/no-style-z-index': 'off',
    'weex/vue/valid-image-component': 'off',
    'weex/vue/valid-style-root': 'off',
    "vue/no-parsing-error": [ 2, {
      "abrupt-closing-of-empty-comment": true,
      "absence-of-digits-in-numeric-character-reference": true,
      "cdata-in-html-content": true,
      "character-reference-outside-unicode-range": true,
      "control-character-in-input-stream": true,
      "control-character-reference": true,
      "eof-before-tag-name": true,
      "eof-in-cdata": true,
      "eof-in-comment": true,
      "eof-in-tag": true,
      "incorrectly-closed-comment": true,
      "incorrectly-opened-comment": true,
      "invalid-first-character-of-tag-name": true,
      "missing-attribute-value": true,
      "missing-end-tag-name": true,
      "missing-semicolon-after-character-reference": true,
      "missing-whitespace-between-attributes": true,
      "nested-comment": true,
      "noncharacter-character-reference": true,
      "noncharacter-in-input-stream": true,
      "null-character-reference": true,
      "surrogate-character-reference": true,
      "surrogate-in-input-stream": true,
      "unexpected-character-in-attribute-name": true,
      "unexpected-character-in-unquoted-attribute-value": true,
      "unexpected-equals-sign-before-attribute-name": true,
      "unexpected-null-character": true,
      "unexpected-question-mark-instead-of-tag-name": true,
      "unexpected-solidus-in-tag": true,
      "unknown-named-character-reference": true,
      "end-tag-with-attributes": true,
      "duplicate-attribute": true,
      "end-tag-with-trailing-solidus": true,
      "non-void-html-element-start-tag-with-trailing-solidus": false,
      "x-invalid-end-tag": false,
      "x-invalid-namespace": true
    }],
    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    // vue mixin filter and other things
    'no-undef': 'off'
  }
}
```

**What did you do? Please include the actual source code causing the issue.**

```vue
<template>
  <div
    :style="{
      width: `${width}px`,
      height: `${height + 1}px`,
      justifyContent: `${textCenter ? 'center' : 'flex-start'}`
    }"
    @click="slotClicked">
    <div>
      <text
        v-if="title"
        :style="{
          textAlign: `${textCenter ? 'center' : 'left'}`,
          marginTop: `${textCenter ? 0 : 14}px`
        }"
        class="title">{{ title }}</text>
      <text
        v-if="desc"
        :style="{
          textAlign: `${textCenter ? 'center' : 'left'}`
        }"
        class="desc">{{ desc }}</text>
    </div>
    <image
      :src="imageUrl"
      :style="{
        width: `${width}px`,
        height: `${height}px`
      }"
      class="img"
      resize="cover" />
    <divider
      v-if="hasDivider"
      :width="width"
      class="divider"></divider>
  </div>
</template>

<script>
import Divider from '../common/Divider'
import { goToApp } from '../../util/app';

export default {
  components: {
    Divider
  },
  props: {
    imageUrl: {
      type: String,
      default: ''
    },
    title: {
      type: String,
      default: ''
    },
    desc: {
      type: String,
      default: ''
    },
    route: {
      type: String,
      default: ''
    },
    width: {
      type: [Number, String],
      default: 750
    },
    ratio: {
      type: [Number, String],
      default: 3.75
    },
    hasDivider: {
      type: Boolean,
      default: true
    },
    textCenter: {
      type: Boolean,
      default: true
    }
  },
  computed: {
    height () {
      return this.width / this.ratio
    }
  },
  methods: {
    slotClicked () {
      goToApp(this.route)
    }
  }
}
</script>

<style scoped>
.img {
  position: absolute;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  width: 750px;
  height: 200px;
}
.title {
  font-size: 28px;
  color: #333333;
  lines: 1;
  text-overflow: ellipsis;
  padding-left: 18px;
  padding-right: 18px;
}
.desc {
  font-size: 24px;
  color: #999999;
  lines: 1;
  text-overflow: ellipsis;
  padding-left: 18px;
  padding-right: 18px;
}
.divider {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
}
</style>

```

**What did you expect to happen?**

不会报错

**What actually happened? Please include the actual, raw output from ESLint.**

vs code 的输出报错

```
[Error - 11:37:39] ESLint stack trace:
[Error - 11:37:39] TypeError: Cannot read property 'name' of undefined
    at prop.body.body.find.p (/Users/quinlanzhong/WeexProjects/mjb-weex-native/node_modules/eslint-plugin-weex/lib/rules/vue/no-document.js:40:35)
    at Array.find (native)
    at hasUsingdocument (/Users/quinlanzhong/WeexProjects/mjb-weex-native/node_modules/eslint-plugin-weex/lib/rules/vue/no-document.js:36:42)
    at propsNode.filter.map.prop (/Users/quinlanzhong/WeexProjects/mjb-weex-native/node_modules/eslint-plugin-weex/lib/rules/vue/no-document.js:53:18)
    at Array.map (native)
    at findPropsWithFunctionExpression (/Users/quinlanzhong/WeexProjects/mjb-weex-native/node_modules/eslint-plugin-weex/lib/rules/vue/no-document.js:52:10)
    at utils.executeOnVue.obj (/Users/quinlanzhong/WeexProjects/mjb-weex-native/node_modules/eslint-plugin-weex/lib/rules/vue/no-document.js:88:43)
    at ExportDefaultDeclaration:exit (/Users/quinlanzhong/WeexProjects/mjb-weex-native/node_modules/eslint-plugin-weex/lib/utils/index.js:470:9)
    at listeners.(anonymous function).forEach.listener (/Users/quinlanzhong/WeexProjects/mjb-weex-native/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (native)
```

**Comment by biaomingzhong** [comment]
goToApp(this.route) 这一行，如果注释掉就不会报错，不用这个方法用任意一个 import 进来的方法都会报错，如果是使用 setTimeout() 也会报错，如下：

```vue
  methods: {
    slotClicked () {
      // goToApp(this.route)
      setTimeout(() => {
        console.log('this is ' + 200)
      }, 200)
    }
  }
```

如果加多一个函数就不会，如下：

```vue
  methods: {
    slotClicked () {
      // goToApp(this.route)
      setTimeout(() => {
        console.log('this is ' + 200)
      }, 200)
    },
    test () {
      console.log(123)
    }
  }
```

**Comment by biaomingzhong** [comment]
@erha19 麻烦看看这个问题

**Comment by erha19** [comment]
@biaomingzhong I will fix it, for now, you can config `no-document` as `off` to turn off this judgment.

**Comment by erha19** [comment]
@biaomingzhong using v1.0.13.

**Comment by biaomingzhong** [comment]
我试试看

**Comment by biaomingzhong** [comment]
试了还会有其他 bug

**Comment by erha19** [comment]
@biaomingzhong add unit test and fix it on `v1.0.14`.
